### ISSUE TITLE
Requirements.txt file is referring to local installations

### ISSUE THREAD

**Issue by roelandpinch** [ShiJiaying/LivePortrait#1]
Great work! 

The `requirements.txt` file is referring to local installations, for example:

```
Brotli @ file:///croot/brotli-split_1714483155106/work
certifi @ file:///croot/certifi_1720453481653/work/certifi
```

It can't find those installations on my machine. I removed the references, but now I'm stuck at 

```
ERROR: Could not find a version that satisfies the requirement MultiScaleDeformableAttention (from versions: none)
ERROR: No matching distribution found for MultiScaleDeformableAttention
```

Not sure how to continue now, any help is appreciated.

**Comment by benhoangquan** [comment]
The error might be related to the installation of X-Pose submodules. I did have the same error when I install stand-alone X-Pose, and IIRC, I solve it with by doing [step 3](https://github.com/IDEA-Research/X-Pose/blob/master/README.md?plain=1#L98) of the environment setup.

**Comment by ShiJiaying** [comment]
Compiling CUDA operators is necessary for  X-Pose, and pay attention to the cuda and torch versions
```
cd XPose/models/UniPose/ops
python setup.py build install
```

**Comment by roelandpinch** [comment]
Thanks, I didn't have CUDA installed and made it a bit further. X-Pose is compiled (although there was a local reference again in https://github.com/ShiJiaying/LivePortrait/blob/a0826343454572c584d2069a58fd9ddfd0ebd584/XPose/models/UniPose/ops/MultiScaleDeformableAttention.egg-info/SOURCES.txt#L4). I fixed the paths to not point to `/work/coda`.
Unfortunately I get stuck now at `uvloop` when running ` pip install -r requirements.txt`:
> RuntimeError: uvloop does not support Windows at the moment

I didn't know it was not suitable for Windows machines. Is there a workaround or does this not work on Windows at all?

**Comment by ShiJiaying** [comment]
> Thanks, I didn't have CUDA installed and made it a bit further. X-Pose is compiled (although there was a local reference again in
> 
> https://github.com/ShiJiaying/LivePortrait/blob/a0826343454572c584d2069a58fd9ddfd0ebd584/XPose/models/UniPose/ops/MultiScaleDeformableAttention.egg-info/SOURCES.txt#L4
> 
> ). I fixed the paths to not point to `/work/coda`.
> Unfortunately I get stuck now at `uvloop` when running ` pip install -r requirements.txt`:
> > RuntimeError: uvloop does not support Windows at the moment
> 
> I didn't know it was not suitable for Windows machines. Is there a workaround or does this not work on Windows at all?

I think uvloop error for Windows is hard to solve. But  `uvloop` is not necessary in this task. 
Maybe you can try to uninstall it and run inference.py

**Comment by roelandpinch** [comment]
yes, thanks. I removed it from the requirements and I was able to compile. Bumped into the next problem, I'm trying to fix it but haven't found a solution yet. It looks like the file `tmpfbbtah2r.py` is being created in a folder (tmp1k8e8bw_ ) that doesn't exist. (I'm running ` python inference.py`).

```
C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\models\UniPose\ops\modules\ms_deform_attn.py:24: UserWarning: Failed to import MSDeformAttnFunction.
  warnings.warn('Failed to import MSDeformAttnFunction.')
Traceback (most recent call last):
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\inference.py", line 7, in <module>
    from src.live_portrait_pipeline import LivePortraitPipeline
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\src\live_portrait_pipeline.py", line 20, in <module>
    from .utils.cropper import Cropper
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\src\utils\cropper.py", line 19, in <module>
    from XPose.app import run_unipose
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\app.py", line 353, in <module>
    model = load_model(config_file, checkpoint_path, cpu_only=False)
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\app.py", line 246, in load_model
    args = Config.fromfile(model_config_path)
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\util\config.py", line 192, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\util\config.py", line 90, in _file2dict
    shutil.copyfile(filename,
  File "C:\Users\Roeland\.conda\envs\LivePortrait\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Roeland\\AppData\\Local\\Temp\\tmp1k8e8bw_\\tmpfbbtah2r.py'
```

**Comment by ShiJiaying** [comment]
> yes, thanks. I removed it from the requirements and I was able to compile. Bumped into the next problem, I'm trying to fix it but haven't found a solution yet. It looks like the file `tmpfbbtah2r.py` is being created in a folder (tmp1k8e8bw_ ) that doesn't exist. (I'm running ` python inference.py`).
> 
> ```
> C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\models\UniPose\ops\modules\ms_deform_attn.py:24: UserWarning: Failed to import MSDeformAttnFunction.
>   warnings.warn('Failed to import MSDeformAttnFunction.')
> Traceback (most recent call last):
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\inference.py", line 7, in <module>
>     from src.live_portrait_pipeline import LivePortraitPipeline
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\src\live_portrait_pipeline.py", line 20, in <module>
>     from .utils.cropper import Cropper
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\src\utils\cropper.py", line 19, in <module>
>     from XPose.app import run_unipose
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\app.py", line 353, in <module>
>     model = load_model(config_file, checkpoint_path, cpu_only=False)
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\app.py", line 246, in load_model
>     args = Config.fromfile(model_config_path)
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\util\config.py", line 192, in fromfile
>     cfg_dict, cfg_text = Config._file2dict(filename)
>   File "C:\Users\Roeland\Documents\LivePortraitAnimals\XPose\util\config.py", line 90, in _file2dict
>     shutil.copyfile(filename,
>   File "C:\Users\Roeland\.conda\envs\LivePortrait\lib\shutil.py", line 256, in copyfile
>     with open(dst, 'wb') as fdst:
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Roeland\\AppData\\Local\\Temp\\tmp1k8e8bw_\\tmpfbbtah2r.py'
> ```

See #2
